# steps:
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 'gcr.io/$PROJECT_ID/amazingapp:$COMMIT_SHA', '.']
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'gcr.io/$PROJECT_ID/amazingapp:$COMMIT_SHA']
#   - name: 'gcr.io/cloud-builders/gcloud'
#     args:
#     - 'run'
#     - 'deploy'
#     - 'amazingapp'
#     - '--image'
#     - 'gcr.io/$PROJECT_ID/amazingapp:$COMMIT_SHA'
#     - '--region'
#     - 'us-east1'
#     - '--platform'
#     - 'managed'
#     - '--allow-unauthenticated'
# images:
#   - gcr.io/$PROJECT_ID/amazingapp:$COMMIT_SHA



steps:
  # Step 1: Debugging - List all the files
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        echo "Checking workspace files...."
        ls -lR /workspace

  # Step 2: Authenticate Docker with Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['auth', 'configure-docker', 'us-central1-docker.pkg.dev']
      
   # Step 2.5: Check if go.mod and go.sum exist
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Checking if go.mod and go.sum exist..."
        if [[ ! -f /workspace/amazingapp/blue/go.mod ]]; then
          echo "🚨 ERROR: go.mod is missing!"
          exit 1
        fi
        if [[ ! -f /workspace/amazingapp/blue/go.sum ]]; then
          echo "🚨 ERROR: go.sum is missing!"
          exit 1
        fi

  # Step 3: Build the Docker image using blue/ as the build context
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/amazingapp-repo/amazingapp:$COMMIT_SHA', '-f', '/workspace/amazingapp/blue/Dockerfile', '/workspace/amazingapp/blue']
  
  # Step 4: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/amazingapp-repo/amazingapp:$COMMIT_SHA']
  
  # Step 5: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'run'
      - 'deploy'
      - 'amazingapp'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/amazingapp-repo/amazingapp:$COMMIT_SHA'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/amazingapp-repo/amazingapp:$COMMIT_SHA


# logbucket: "gs://725837802412-global-cloudbuild-logs"