steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/amazingapp:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/amazingapp:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'  # Deploy to Cloud Run
  args: ['run', 'deploy', 'amazingapp', '--image', 'gcr.io/$PROJECT_ID/amazingapp:$COMMIT_SHA', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']  # Deploy to Cloud Run
images:
- 'gcr.io/$PROJECT_ID/amazingapp:$COMMIT_SHA' 

#please commit#
